conda_build_tool: rattler-build
bot:
  automerge: version
  version_updates:
    sources:
    - github

shellcheck:
  enabled: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
